version: '3'
services:
  express1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000"
    networks:
      - portainer_agent_network  

networks:
  portainer_agent_network:
    driver: overlay   
    external: true   