version: '2'
services:
  express1:
    build:
      context: .
    ports:
      - "3000"
    networks:
      - portainer_agent_network  

networks:
  portainer_agent_network:
    driver: overlay      